In [1]:
# 1. Using qtorch to tensor

import torch
from qtorch.quant import Quantizer, quantizer
from qtorch import FloatingPoint

In [2]:
random_input = torch.rand([3,3])
print(random_input)

tensor([[0.9562, 0.8024, 0.3401],
        [0.8613, 0.9098, 0.8928],
        [0.9854, 0.6158, 0.6871]])


In [3]:
constant_input = torch.tensor([[255., -255.],[1.4, 1.6]])
print(constant_input)

tensor([[ 255.0000, -255.0000],
        [   1.4000,    1.6000]])


In [4]:
# Set quantizer
bit = FloatingPoint(exp=2, man=1)
quant = quantizer(forward_number=bit, forward_rounding="nearest")

In [5]:
random_output = quant(random_input)
print(random_output)

tensor([[1.0000, 0.7500, 0.5000],
        [0.7500, 1.0000, 1.0000],
        [1.0000, 0.5000, 0.7500]])


In [6]:
constant_output = quant(constant_input)
print(constant_output)

tensor([[ 3.0000, -3.0000],
        [ 1.5000,  1.5000]])
